version: '3'

services:
  proxy:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: proxy
    ports:
      - "9999:8080"
    volumes:
      - ../config.yaml:/config.yaml
    environment:
      - API_KEY=xxx
      - CONF_PATH=/config.yaml
      - REQ_LIMIT=10000
      # - HTTP_PROXY=xxx
      - REDIS_HOST=localhost:6379
      # - REDIS_PASS=xxx

